### ISSUE TITLE
Python files marked as "clike"

### ISSUE THREAD

**Issue by foresmac** [vokal/cvr#35]
Here's an example:

<img width="1224" alt="screen shot 2015-10-28 at 1 52 34 pm" src="https://cloud.githubusercontent.com/assets/3628189/10799562/776b9a84-7d7b-11e5-9d20-d23a5b820379.png">

I presume this is use for syntax highlighting? Probably pretty safe to just assume any file that ends in `.py` is a Python file.

**Comment by jrit** [comment]
I think like 324 in https://github.com/vokal/cvr/blob/master/source/index.js should be `py: "python",`
